// Vercel Serverless Function for the Taplio MCP server.
//
// This is a thin ESM entry that imports a PRE-BUNDLED, self-contained handler
// (api/_handler.mjs, generated by `npm run bundle`). Bundling ahead of time
// avoids Vercel compiling our TypeScript / resolving ESM imports at deploy time,
// which is what previously caused FUNCTION_INVOCATION_FAILED.
//
// Env vars (set in the Vercel dashboard, encrypted):
//   - TAPLIO_API_KEY     : your Taplio API key (server-side only)
//   - MCP_SHARED_SECRET  : token clients must present in the URL (?token=...)
//   - TAPLIO_READONLY    : optional "true" to block all write tools
import { createHttpHandler } from "./_handler.mjs";

const handler = createHttpHandler();

export default function (req, res) {
  return handler(req, res);
}
